name: wallet_hd
description: A Flutter package project , it is use for HD wallet . Support BTC, ETH, ERC20-USDT transfer signature.
version: 0.0.3
homepage: https://github.com/shareven/wallet_hd

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  bip39: ^1.0.6
  bs58check: ^1.0.2
  bech32: ^0.2.2
  meta: ^1.17.0
  web3dart: ^2.7.3
  typed_data: ^1.4.0
  pointycastle: ^3.9.1
  hex: ^0.2.0
  crypton: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
